all:
	gcc demo01_选择法.c -o demo01_选择法.elf
	gcc demo02_插入.c -o demo02_插入.elf
	gcc demo03_冒泡.c -o demo03_冒泡.elf
	gcc demo04_希尔排序法.c -o demo04_希尔排序法.elf
	gcc demo05_快速排序.c -o demo05_快速排序.elf
	gcc demo06_归并算法.c -o demo06_归并算法.elf
clean:
	rm -rf *.elf