all:
	g++ reload_overwrite.cpp -o reload_overwrite
	g++ vptr.cpp -o vptr
	g++ creat_vptr.cpp -o creat_vptr
	g++ p_c.cpp -o p_c
	g++ virtual_destroy.cpp -o virtual_destroy
	g++ abstract.cpp -o abstract
	g++ mul_extends.cpp -o mul_extends
clean:
	rm -rf reload_overwrite vptr creat_vptr p_c virtual_destroy abstract mul_extends
