all:
	g++ extends.cpp -o extends
	g++ extends2.cpp -o extends2
	g++ extends3.cpp -o extends3
	g++ ex_creat.cpp -o ex_creat
	g++ static.cpp -o static
	g++ mul_extends.cpp -o mul_extends
	g++ mul_state.cpp -o mul_state
	g++ virtual_state.cpp -o virtual_state
	g++ mul_state2.cpp -o mul_state2
clean:
	rm -rf extends extends2 extends3 ex_creat static mul_extends mul_state virtual_state mul_state2
