all:
	g++ copy.cpp -o copy
	g++ copy1.cpp -o copy1
	g++ copy2.cpp -o copy2
	g++ creat.cpp -o creat
	g++ creat2.cpp -o creat2
	g++ creat3.cpp -o creat3
	g++ creat4.cpp -o creat4
	g++ new_delete.cpp -o new_delete
	g++ new_delete2.cpp -o new_delete2
	g++ new_delete3.cpp -o new_delete3
	g++ static.cpp -o static
	g++ static2.cpp Test3.cpp -o static2
clean:
	rm -rf copy copy1 copy2 creat creat2 creat3 creat4 new_delete new_delete2 new_delete3 static static2
