all:
	g++ yinyong.cpp -o yinyong
	g++ yinyong1.cpp -o yinyong1
	g++ yinyong2.cpp -o yinyong2
	g++ yinyong3.cpp -o yinyong3
	g++ yinyong_p.cpp -o yinyong_p
	g++ yinyong_const.cpp -o yinyong_const
	g++ inline.cpp -o inline
	g++ default.cpp -o default
	g++ occ.cpp -o occ
	g++ reload.cpp -o reload
	g++ reload_p.cpp -o reload_p
	g++ creat.cpp -o creat
clean:
	rm -rf yinyong yinyong1 yinyong2 yinyong3 yinyong_p yinyong_const inline default occ reload reload_p creat
