all:
	g++ clientsocket.c -o clientsocket
	g++ secpoint.c -o secpoint
	g++ demo01_sort.c -o demo01_sort
	g++ demo02_type.c -o demo02_type
	g++ mem_test.c -o mem_test
	g++ global_test.c -o global_test
	g++ heap_stack.c -o heap_stack
	g++ memcpy_test.c -o memcpy_test
clean:
	rm -rf clientsocket secpoint demo01_sort demo02_type mem_test global_test heap_stack
