all:
	g++ array_point.c -o array_point
	g++ array2_point.c -o array2_point
	g++ array2_addr.c -o array2_addr
	g++ array2_func.c -o array2_func
	g++ array2_test.c -o array2_test
	g++ array2_mem.c -o array2_mem
clean:
	rm -rf array_point array2_point array2_addr array2_func array2_test array2_mem
