all:
	g++ demo1.cpp -o demo1
	g++ demo2.cpp -o demo2 
	g++ namespace.cpp -o namespace
	g++ namespace2.cpp -o namespace2
	g++ register.cpp -o register
	g++ global.cpp -o global
	g++ struct.cpp -o struct
#	g++ variabel.cpp -o variabel
	g++ bool.cpp -o bool
	g++ thrun.cpp -o thrun
	g++ const.cpp -o const
	g++ yinyong.cpp -o yinyong -fpermissive
clean:
	rm -rf demo1 demo2 namespace namespace2 register global struct variabel bool thrun const yinyong
