all:
	g++ vector.cpp -o vector
	g++ vector2.cpp -o vector2
	g++ stack.cpp -o stack
	g++ stack2.cpp -o stack2
	g++ queue.cpp -o queue
	g++ queue2.cpp -o queue2
	g++ list_iterator.cpp -o list_iterator
	g++ stl_sort.cpp -o stl_sort
	g++ map.cpp -o map	

clean:
	rm -rf vector vector2 stack stack2 queue queue2 list_iterator stl_sort map
