all:
	g++ point.c -o point
	g++ nullpoint.c -o nullpoint
	g++ handle_nullpoint.c -o handle_nullpoint
	g++ struct_array.c -o struct_array
	g++ struct_copy.c -o struct_copy
	g++ struct_size.c -o struct_size
	g++ struct_point.c -o struct_point
	g++ struct_point2.c -o struct_point2
	g++ struct_copy_adv.c -o struct_copy_adv
	g++ struct_copy_adv2.c -o struct_copy_adv2
clean:
	rm -rf point nullpoint handle_nullpoint struct_array struct_size struct_point struct_copy struct_point2 struct_copy_adv struct_copy_adv2
