all:
	g++ global_this.cpp -o global_this
	g++ chain.cpp -o chain
	g++ friend.cpp -o friend
	g++ friend2.cpp -o friend2
	g++ operator_reload.cpp -o operator_reload
	g++ operator_reload2.cpp -o operator_reload2
	g++ operator_reload3.cpp -o operator_reload3
clean:
	rm -rf global_this chain friend friend2 operator_reload operator_reload2 operator_reload3
